#!/bin/bash
set -e
source pipe-tools-utils

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
ASSETS=${THIS_SCRIPT_DIR}/../assets
ARGS=( \
  DATE_RANGE \
  MESSAGES_TABLE \
  SEGMENT_INFO_TABLE \
  SEGMENT_VESSEL_TABLE \
  TRACKS_TABLE \
)

################################################################################
# Validate and extract arguments
################################################################################
display_usage() {
  ARG_NAMES=$(echo "${ARGS[*]}")
  echo -e "\nUsage:\n$0 $ARG_NAMES\n"
}

if [[ $# -ne ${#ARGS[@]} ]]
then
    display_usage
    exit 1
fi

echo "Running $0"
ARG_VALUES=("$@")
PARAMS=()
for index in ${!ARGS[*]}; do
  echo "  ${ARGS[$index]}=${ARG_VALUES[$index]}"
  declare "${ARGS[$index]}"="${ARG_VALUES[$index]}"
done

IFS=, read START_DATE END_DATE <<<"${DATE_RANGE}"
if [ -z $END_DATE ] || [ $END_DATE == $START_DATE ]; then
  END_DATE=$(date +%Y-%m-%d -d "$START_DATE + 1 day")
fi
################################################################################
# Generating tracks table
################################################################################
TABLE_DESC=(
  "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
  "* Sources: ${MESSAGES_TABLE} ${SEGMENT_INFO_TABLE} ${SEGMENT_VESSEL_TABLE}"
  "* Command:"
  "$(basename $0)"
  "$@"
)
TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )
echo "Publishing tracks to ${TRACKS_TABLE}..."
echo "${TABLE_DESC}"
SCHEMA=${ASSETS}/bigquery/tracks.schema.json
bq --headless mk \
  --force \
  --description "${TABLE_DESC}" \
  --schema ${SCHEMA} \
  --time_partitioning_field timestamp \
  --clustering_fields seg_id,vessel_id \
  ${TRACKS_TABLE}
if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${TRACKS_TABLE}"
  exit 1
fi

################################################################################
# Clean up existing records
################################################################################
echo "Deleting existing records for table ${TRACKS_TABLE}"
DELETE_SQL=${ASSETS}/bigquery/delete.sql.j2
jinja2 ${DELETE_SQL} \
  -D table=${TRACKS_TABLE//:/.} \
  -D start=${START_DATE} \
  -D end=${END_DATE} \
   | bq --headless query
if [ "$?" -ne 0 ]; then
  echo "  Unable to delete records for table ${TRACKS_TABLE}"
  exit 1
fi
echo "  Deleted existing records in ${TRACKS_TABLE}"

################################################################################
# Inserting new records
################################################################################
echo "Inserting new records for table ${TRACKS_TABLE}"
INSERT_SQL=${ASSETS}/bigquery/aggregate-tracks.sql.j2
jinja2 ${INSERT_SQL} \
   -D source=${MESSAGES_TABLE//:/.} \
   -D start_yyyymmdd=$(yyyymmdd ${START_DATE}) \
   -D end_yyyymmdd=$(yyyymmdd ${END_DATE}) \
   -D segment_info=${SEGMENT_INFO_TABLE//:/.} \
   -D segment_vessel=${SEGMENT_VESSEL_TABLE//:/.} \
   | bq --headless query \
    -n 0 \
    --destination_table ${TRACKS_TABLE} \
    --append_table
if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${TRACKS_TABLE}"
  exit 1
fi
echo "  Inserted new records for table ${TRACKS_TABLE}"

echo "${TRACKS_TABLE} Done."
