#!/bin/bash
source pipe-tools-utils

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"
ASSETS=${THIS_SCRIPT_DIR}/../assets
source ${THIS_SCRIPT_DIR}/pipeline.sh

display_usage() {
  echo -e "\nUsage:\n$0 MESSAGES_TABLE TRACKS_TABLE\n"
}

if [[ $# -ne 2  ]]
then
    display_usage
    exit 1
fi

MESSAGES_TABLE=$1
TRACKS_TABLE=$2

DELETE_SQL=${ASSETS}/bigquery/delete.sql.j2
INSERT_SQL=${ASSETS}/bigquery/aggregate-tracks.sql.j2
SCHEMA=${ASSETS}/bigquery/tracks.schema.json
TABLE_DESC=(
  "* Pipeline: ${PIPELINE} ${PIPELINE_VERSION}"
  "* Source: ${MESSAGES_TABLE}"
  "* Command:"
  "$(basename $0)"
  "$@"
)
TABLE_DESC=$( IFS=$'\n'; echo "${TABLE_DESC[*]}" )


echo "Publishing tracks to ${TRACKS_TABLE}..."
echo "${TABLE_DESC}"

echo "  Create table"

bq mk --force \
  --description "${TABLE_DESC}" \
  --schema ${SCHEMA} \
  ${TRACKS_TABLE}

if [ "$?" -ne 0 ]; then
  echo "  Unable to create table ${TRACKS_TABLE}"
  exit 1
fi

echo "  Deleting existing records for table ${TRACKS_TABLE}"

jinja2 ${DELETE_SQL} -D table=${TRACKS_TABLE//:/.} \
     | bq query --max_rows=0

if [ "$?" -ne 0 ]; then
  echo "  Unable to delete records for table ${TRACKS_TABLE}"
  exit 1
fi

echo "  Inserting new records for table ${TRACKS_TABLE}"

jinja2 ${INSERT_SQL} \
   -D source=${MESSAGES_TABLE//:/.} \
   -D dest=${TRACKS_TABLE//:/.} \
   | bq query --max_rows=0

if [ "$?" -ne 0 ]; then
  echo "  Unable to insert records for table ${TRACKS_TABLE}"
  exit 1
fi

echo "  ${TRACKS_TABLE} Done."
