#!/usr/bin/env bash

THIS_SCRIPT_DIR="$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )"

display_usage() {
	echo "Available Commands"
	echo "  aggregate_tracks                   aggregate messages into tracks and publish to bigquery"
  echo "  publish_postgres                   publish tracks from a given bigquery table to postgis"
	}


if [[ $# -le 0 ]]
then
    display_usage
    exit 1
fi


case $1 in

  aggregate_tracks)
    ${THIS_SCRIPT_DIR}/aggregate_tracks "${@:2}"
    ;;

  publish_postgres)
    ${THIS_SCRIPT_DIR}/publish_postgres "${@:2}"
    ;;

  *)
    display_usage
    exit 1
    ;;
esac
